# Generated by Django 3.1b1 on 2020-06-24 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=17, unique=True)),
                ('currency', models.CharField(choices=[('1', 'Gbp'), ('2', 'Eur')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LloydsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(default='')),
                ('debited', models.IntegerField(default=0)),
                ('credited', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
